# Generated by Django 6.0.7 on 2026-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimage_project_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryproject',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
