# Generated by Django 6.0.7 on 2026-07-13 14:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_galleryproject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
